#pragma once

#define IOE_DEBUG_ENABLED					IOE_ON
#define IOE_MEMORY_DEBUG					IOE_OFF
#define IOE_ASSERT_ENABLED					IOE_ON
#define IOE_SHADER_DEBUG					IOE_ON
#define IOE_RPI_PROFILE_MARKERS				IOE_ON